### ISSUE TITLE
可以支持配合鼠标滚动实现桌面切换吗？

### ISSUE THREAD

**Issue by zeyios** [Vonng/Capslock#32]
**Is your feature request related to a problem? Please describe.**
在mac配合使用鼠标的时候，左右切换桌面比较难操作，我现在使用 caps+q / e 来实现左右切换桌面。

**Describe the solution you'd like**
可以支持按下caps，同时滚动鼠标轮轴就可以左右切换桌面吗？

**Comment by miozus** [comment]
```yaml

################################################################
#                        Hyper MouseKey                        #
################################################################
  - description: Hyper MouseKey
    manipulators:
    #==========================================================#
    # (  mouse wheel )  ->    ( desktop switch )               #
    #==========================================================#
    - description: 'mouse_wheel_up = ctrl + left (prev desktop)'
      type: basic
      from: { mouse_key: { vertical_wheel: -32 }: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
      to: [ { key_code: left_arrow , modifiers: [ left_control ] } ]
    - description: 'mouse_wheel_down = ctrl + right (next desktop)'
      type: basic
      from: { mouse_key: { vertical_wheel: 32 }: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
      to: [ { key_code: left_arrow , modifiers: [ left_control ] } ]
```
按住caps同时滚动鼠标轮轴就可以左右切换桌面的实现.yml

拿源码改的，思路这样，YAML 和 JSON 差不多，你试着复制和修改进 capslock.json，然后测试（我没鼠标）
